name: Github Action Test
on: [push]

jobs:
  All:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-verson: 1.8

      - shell: bash
        run: |
          mvn -B package --file pom.xml
          echo "Build Project"
          mvn compile
          echo "Run Junit"
          mvn test